name: Auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  enable_automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PRs
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.PR_GITHUB_TOKEN}}
